### ISSUE TITLE
Re-ordered

### ISSUE THREAD

**Issue by zkisaboss** [kuel27/wordlist#1]
https://raw.githubusercontent.com/zkisaboss/reorderedwordlist/main/output.txt

I organized your list in Python with kaggle.com's English Word Frequency Dataset. You can double-check for missing terms on diffchecker.com; however, I found none.

**Comment by kuel27** [comment]
the list you've provided appears to have a couple of issues: some words contain an apostrophe, which, to my knowledge, is not in the game. Some words have initial capital letters which isn't necessary, and certain words have been modified for reasons I'm unsure of (for example, "addida" being changed to "addidas").

additionally, I'm uncertain if this is necessarily the optimal order. I think that the words in the game are picked truly randomly, meaning each word has an equal probability (expect the human psychological factor making some words perhaps more common)
